# This is a basic workflow to help you get started with Actions

name: Code Review With LLM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, synchronize]
    paths: ['**.py', '**.sql']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cortex_review"
  cortex_review:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch the head of the PR branch
          fetch-depth: 0 # Ensures full history is available for diffing against base

      # Set up python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install snowflake-connector-python
          
      - name: Extract PR diff
        id: diff
        run: |
          # Fetch the base branch of the PR to ensure it's up-to-date locally
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Generate the diff between the base branch and the PR HEAD
          # The '...' syntax ensures we only get changes introduced by the PR branch
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD > diff_code_to_review.txt
          
          echo "Diff successfully generated to abc.txt"
          ls -l diff_code_to_review.txt # Optional: to confirm the file exists and its size

      - name: Upload diff.txt as an artifact 
        uses: actions/upload-artifact@v4
        with:
          name: pr-diff-file
          path: diff_code_to_review.txt # Optional: retention-days: 5 # How long to keep the artifact
          
